name: Yad2 Scraper

on:
  schedule:
    - cron: '*/15 5-17 * * *'  # Run every 15 minutes from 05:00 to 17:00 UTC
  workflow_dispatch:           # Allows manual runs

jobs:
  scraper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js (v20)
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install packages
        run: yarn install

      - name: Ensure data directory exists
        run: mkdir -p data

      - name: Run scraper
        run: |
          export API_TOKEN=${{ secrets.API_TOKEN }}
          export CHAT_ID=${{ secrets.CHAT_ID }}
          yarn scrape

      - name: Push new JSON data if needed
        run: |
          if [ -f ./push_me ]; then
            echo Pushing to Github...
            git add .
            DATE=$(date +"%F, %H:%M:%S")
            git commit -m "updated data - $DATE"
            git push
          fi
